export const EVENTS = {
  USER_REGISTERED: "USER_REGISTERED",
  CHAT_STARTED: "CHAT_STARTED",
  MESSAGE_SENT: "MESSAGE_SENT",
  CHAT_ENDED: "CHAT_ENDED",
  FEEDBACK_SUBMITTED: "FEEDBACK_SUBMITTED",
  SUPPORT_ESCALATED: "SUPPORT_ESCALATED"
};
